add info about deprecation to readme
AirHelp/flask-rage pull request #67
Opened 2021-11-09 11:29 UTC by piotr-sepiol

2021-11-09 11:30 UTC, pmaciejp approved these changes

2021-11-09 11:32 UTC, niedziela requested changes

2021-11-09 11:32 UTC, niedziela commented on README.md
> +###This is no longer supported
add space

2021-11-09 11:32 UTC, mpaliwoda commented on README.md
> +###This is no longer supported
need a space here :D 

also maybe we'd want to add a specific date when we'll delete the repo so everybody's got the timeframe to act upon this info?

2021-11-09 13:45 UTC, piotr-sepiol commented on README.md
> +###This is no longer supported
I don't know if we want to delete this repo 🤷

2021-11-09 15:27 UTC, mpaliwoda commented on README.md
> +###This is no longer supported
ah ok, so just archiving or sth?

2021-11-09 15:28 UTC, mpaliwoda approved these changes

2021-11-09 15:58 UTC, niedziela approved these changes

2021-11-10 11:25 UTC, piotr-sepiol commented on README.md
> +###This is no longer supported
I added info about archiving

2021-11-10 11:26 UTC, mpaliwoda approved these changes
👍

2021-11-10 11:28 UTC, niedziela commented
👍

2021-11-10 11:30 UTC, merged